### PR TITLE
simple refactor of this project 

### PR DESCRIPTION
**Pull request by aclgo**

### CODE REVIEW

**Review by jeffotoni — COMMENTED** [review]
validate to test and see if it won't break the functions

**Comment by jeffotoni** [comment]
Change made I will play for V2 as it is we cannot go up, it will break the package it is not possible to break it.

**Comment by aclgo** [comment]
ok

**Comment by Guilherme-De-Marchi-s3wf** [comment]
I refactored the code and removed the profiles, because we thought it would be better to keep the responsibility for organizing the profiles outside of the library. But thanks for your contribution, @aclgo!

**Pull request merged**
